### ISSUE TITLE
[3pt]  - Create feature: add  new like - Student A

### ISSUE THREAD

**Issue by AbbasSarwar** [AbbasSarwar/Shows#9]
When the user clicks on the Like button of an item (on Homepage), the interaction is recorded in the Involvement API and the screen is updated.

**Comment by zunairkhan811** [comment]
I am closing this issue as this has approved in the pull request below
[Pull Request](https://github.com/AbbasSarwar/Shows/pull/28#pullrequestreview-1393890431)
